### ISSUE TITLE
Controller does not work with this mod

### ISSUE THREAD

**Issue by pagem** [RandyKnapp/ValheimMods#7] opened 2021-02-25 11:42 UTC
Been using an Xbox controller fine. Installed this mod along with BepInExPac and the controller stops working. Uninstalled this mod, leaving BepInExPac, and the controller starts working again fine, so believe the problem lies in this mod. Shame as it looks excellent.

**Comment by Outwise** [comment] 2021-02-26 03:15
I also use the xbox controller and this mod, but haven't had problems with not working, though I havent thoroughly tested it in the new UI elements for any control flip glitch. 
Does the controller immediately not work for you, or does it stop at some point during play? if so, do you know when?

Are you launching the game via Steam (I believe this is the only current way barring some workaround)? I originally had a problem (playing vanilla) with my controller suddenly changing mappings due to some edge case interaction with the UI (left trigger to right trigger, no right trigger input anymore). I think that is a specific bug with how they implemented the steam control configs - **when I disabled Steam's "compatibility" option with xbox controllers** (disabling custom input mappings), the controller is received as just a normal xbox controller and not via the Steam controller API, which seems to have eliminated that problem for me. 

I hope that helps, if not maybe your response with reproduction details will help identify the problem!

**Comment by pagem** [comment] 2021-02-26 12:36
> I also use the xbox controller and this mod, but haven't had problems with not working, though I havent thoroughly tested it in the new UI elements for any control flip glitch.
> Does the controller immediately not work for you, or does it stop at some point during play? if so, do you know when?
> 
> Are you launching the game via Steam (I believe this is the only current way barring some workaround)? I originally had a problem (playing vanilla) with my controller suddenly changing mappings due to some edge case interaction with the UI (left trigger to right trigger, no right trigger input anymore). I think that is a specific bug with how they implemented the steam control configs - **when I disabled Steam's "compatibility" option with xbox controllers** (disabling custom input mappings), the controller is received as just a normal xbox controller and not via the Steam controller API, which seems to have eliminated that problem for me.
> 
> I hope that helps, if not maybe your response with reproduction details will help identify the problem!

Yes the controller is just dead from launch. 

I am starting the game from within the r2modman app, Valheim -> Start Modded.

I do have the Steam compatibility settings on so will remove them and see if that helps. Will confirm. After uninstalling the mod I lost the equipped gear (armour set). I will backup the game file first this time. 

Sidenote: I have also had the trigger swap issue but only if I start the game before connecting the controller.

**Comment by RandyKnapp** [comment] 2021-03-05 19:32
Fixed in EquipmentAndQuickSlots 1.0.4

**Closed by RandyKnapp** 2021-03-05 19:32 UTC
