### ISSUE TITLE
[EquipmentAndQuickslots] All EquipmentAndQuickslots Lost on Death in 2.0.4

### ISSUE THREAD

**Issue by M4R5W0N6** [RandyKnapp/ValheimMods#139] opened 2021-04-16 05:20 UTC
I know this was supposedly patched in 2.0.2 but, alas.

Here is a list of all of the mods running when this occurred:
BepInEx 5.4.901
ExtendedItemDataFramework 1.0.0
BetterUI 2.0.1
EpicLoot 0.7.6
ServerSideMap 1.3.1
ValheimFaveServers 1.0.1
EquipWheel 1.3.3
Troll_Visual_Upgrade 1.2.0
InstantMonsterLoopDrop 0.2.11
ValheimLib 0.0.15
HookGenPatcher 0.0.2
Basement 1.0.0
SkillInjector 1.1.1
Moreskills 1.10.1
EquipmentAndQuickslots 2.0.4
FloatingItems 1.0.0
FasterTeleportation 0.3.1
Change_Forsaken_Power 0.1.4
TeleportWolves 0.2.1
Useful_Trophies 1.1.0
EmoteWheel 1.3.0
BetterArchery 1.6.2
CropReplant 2.1.1

And here is the Thunderstore Code: 18VGWl5cIA
Cheers!

**Comment by M4R5W0N6** [comment] 2021-04-16 06:05
Sidenote: pretty sure my inventory was also full when I died -- might need to increase the tombstone size to encompass your added slots (or add that mod Gravekeeper) as a dependancy on Thunderstore? BetterArchery also just drops your quiver slots on the ground so that's another option.

**Comment by M4R5W0N6** [comment] 2021-04-16 06:22
Also related: items will not auto-pickup even with empty inventory slots if the number of full inventory slots plus the number of full EquipmentAndQuickslots are equal to or greater than the **base** inventory size. Is there a way you can increase that base inventory size or is there another mod that your utilizing to do that? Cheers.

**Comment by SerinitySW** [comment] 2021-04-16 14:42
Also have lost my inventory, twice. Once when I 'ragequit' (jokingly), and once when my friend got something out of my grave.

**Comment by AlexandruVerenca** [comment] 2021-04-23 08:36
Can confirm, full inventory on death usually means  one or every armor item gets lost. I sometimes just lose my belt, other times, every piece of armor I had on.

**Comment by RandyKnapp** [comment] 2021-04-26 12:59
This is a video of what it looks like when I go to pick up a tombstone that got created when I die with a full inventory. Is that what it  looks like for you folks? If not, could you please share a video or detailed description of exactly what happens?

https://user-images.githubusercontent.com/3331569/116086362-97d95b00-a654-11eb-9b57-c5862cde3dcd.mp4

**Comment by duebbers** [comment] 2021-04-26 13:02
Same here - I think it is not the death itself, but the looting of the grave. The problem only occurs when the inventory and the equipment slots were full. If you loot the grave then normaly the grave would stay as long as you don't have space for all the items in the grave. But here it tries to transfer all items to their former place, fails with the equipment slots but destroys the grave nonetheless.

**Comment by RandyKnapp** [comment] 2021-04-26 13:08
Let me try with a set of lighter things

**Comment by duebbers** [comment] 2021-04-26 13:08
oh, you added the video while I was typing :-)

I wasn't shown the inventory and grave (as it would normaly do with an overflowing inventory). On picking up the grave I just got the 'Item recovered'-hint as if I had enough space and the grave exploded.

**Comment by RandyKnapp** [comment] 2021-04-26 14:25
Folks, I know this is a really important and essential bug to fix, but I cannot reproduce it. I need very specific repro steps from you all:
(If you can, try to reproduce it without any other mods installed except EAQS and EIDF)
1. What exactly was in your inventory?
2. What did you have equipped?
3. Turn on logging for EAQS in the config and send your player log
4. Record a video of the bug happening (press Windows+G to open game center, and you can record gameplay there)

**Comment by sbtoonz** [comment] 2021-04-26 14:31
personally still trying to track down the source of this one as I suffer it as well 

I am leaning towards the belief tis another mod interfering at this point since I can't replicate with only extended items/quickslots

**Comment by aydnblakk** [comment] 2021-04-27 02:18
Happened to me earlier today in the swamp, lost all my Bronze equipment T-T Looks like none of my previous equipment went into their slots when I hit Take All, and my grave went poof.

Here's the mods I'm using (probably using too many tbh):
AutoRepair by Tekla
BepInExPack_Valheim by denikson
BetterArchery by ishid4
BetterUI by Masa
CombatOverhaul by Kyresel
CookingSkill by thegreyham
CraftingWithContainers by abearcodes
EnhancedPotions by hbocao
EpicLoot by RandyKnapp
EquipmentAndQuickslots by RandyKnapp
ExtendedItemDataFramework by RandyKnapp
HoneyPlus by OhhLoz
HookGenPatcher by ValheimModding
JotunnLib by JotunnLibTeam
MoreSkills by guiriguy
Move_Piece by KG
NoStaminaSneak by MrPurple6411
PotionPlus by OdinPlus
SimpleRecycling by abearcodes
SkillInjector by pipakin
Terraheim by DasSauerkraut
TripleBronze by KaceCottam
Troll_Visual_Upgrade by Eskylar
UnfrightenTamedAnimals by chase000
Valheim_Legends by Torann
ValheimLib by ValheimModding

Good luck debugging what the issue is!

**Comment by aydnblakk** [comment] 2021-04-27 02:54
> Happened to me earlier today in the swamp, lost all my Bronze equipment T-T Looks like none of my previous equipment went into their slots when I hit Take All, and my grave went poof.

I came home to start making new equipment, and I'm seeing the equipment that I lost (Troll Leather Helmet, Wood Tower Shield, Bronze Plate Cuirass) as options in the enchant window. 

You can see that they're not in my inventory but available to Enchant, so I'm wondering if they went somewhere I can't access in my equipment/inventory windows?

**Comment by duebbers** [comment] 2021-04-27 06:53
> I came home to start making new equipment, and I'm seeing the equipment that I lost (Troll Leather Helmet, Wood Tower Shield, Bronze Plate Cuirass) as options in the enchant window.
> 
> You can see that they're not in my inventory but available to Enchant, so I'm wondering if they went somewhere I can't access in my equipment/inventory windows?


It would be very interesting if the Items are not lost, but just hidden.
You use the `CraftingWithContainers `mod - is it possible that it also works with enchanting and that you have a spare Troll-Set somewhere in your chests?

**Comment by RandyKnapp** [comment] 2021-04-27 20:07
@duebbers @M4R5W0N6 @aydnblakk @sbtoonz @SerinitySW @AlexandruVerenca 

Just uploaded a new version here: https://www.nexusmods.com/valheim/mods/92?tab=files

Can you all please download and try it out? Please continue to report issues here.

**Comment by sbtoonz** [comment] 2021-04-27 20:10
Waiting for it to post latest ver I am on is compiled from your git source looked like my most recent hash for that portion was b483142e5fbc63d9b59e29fa1c48170c64213bf7


I will update would you prefer I use nexus or can I just pull down git changes and compile from clean source base?

**Comment by RandyKnapp** [comment] 2021-04-27 20:26
The latest is bc9308c, sorry I made this post before I pushed

**Comment by sbtoonz** [comment] 2021-04-27 22:01
> The latest is [bc9308c](https://github.com/RandyKnapp/ValheimMods/commit/bc9308c3bb28887e6bf516125eec6e7993e2d31f), sorry I made this post before I pushed

SO far so good cannot replicate previous scenario at all will have some of my players update and see if it fixes for them

**Comment by sbtoonz** [comment] 2021-04-28 15:59
bc9308c resolves my issues

**Comment by aydnblakk** [comment] 2021-04-30 06:51
> It would be very interesting if the Items are not lost, but just hidden.
> You use the `CraftingWithContainers `mod - is it possible that it also works with enchanting and that you have a spare Set somewhere in your chests?

One workaround I found is upgrading the items will bring them back into my inventory, so that was neat. I just recycled the rest and got most of the raw mats back into my inventory.

I ended up disabling CraftingWithContainers, I'm convinced that mod somehow made this stuff happen, but I haven't died yet to try and replicate it. And I got the GraveKeeper mod so I'm not gonna go through that again 😅

**Comment by virtualbjorn** [comment] 2021-04-30 08:51
Still lost everything on the new slots. version 2.0.5

**Comment by sbtoonz** [comment] 2021-04-30 14:29
> > It would be very interesting if the Items are not lost, but just hidden.
> > You use the `CraftingWithContainers `mod - is it possible that it also works with enchanting and that you have a spare Set somewhere in your chests?
> 
> One workaround I found is upgrading the items will bring them back into my inventory, so that was neat. I just recycled the rest and got most of the raw mats back into my inventory.
> 
> I ended up disabling CraftingWithContainers, I'm convinced that mod somehow made this stuff happen, but I haven't died yet to try and replicate it. And I got the GraveKeeper mod so I'm not gonna go through that again 😅

Death Tweaks by AedenThorn seems to have options specifically catered to equipment and quickslots and has been serving me well since switching from gravekeeper

**Comment by jsza** [comment] 2021-05-12 23:08
For posterity, I think this particular issue should be fixed in EAQS 2.0.6.

**Comment by aidalgol** [comment] 2021-12-07 09:52
I just encountered this bug while playing on a server.  Got killed by an Elite Draugur in the swamp, and respawned in my bed with no items.
# Version Info
- Valheim 0.205.0
- Dedicated server devcommands 1.4.0
- EAQs 2.0.14
- Better Archer 1.7.0
- Better Archery EAQS Fix 0.0.2
- MassFarming 1.3
- Better Wagon 1.1.0
- Fishing Overhaul 1.1
- Floating Items 1.0.0
- Valheim Recycle 2.0.0
- Build Camera 1.6.1

**Closed** 2022-12-31 16:06 UTC
Labels: bug, EquipmentAndQuickSlots
