### ISSUE TITLE
Hard crashing on hitting deer

### ISSUE THREAD

**Issue by SuntooX** [RandyKnapp/ValheimMods#143] opened 2021-04-19 14:36 UTC
Hey, I've been having an odd issue where any damage to deer will result in a hard crash without logged error (on linux).
I just tried it on a fresh install with the following bepinex*** package.
[denikson-BepInExPack_Valheim-5.4.901.zip](https://github.com/RandyKnapp/ValheimMods/files/6336864/denikson-BepInExPack_Valheim-5.4.901.zip)

Let me know any details you need.

Thanks! Id love to not crash whenever my wolves get hungry...

**Comment by DarkSir23** [comment] 2021-04-22 02:53
I, too, am experiencing this.  Also Linux.  Occasionally happening under other circumstances, but I can replicate it pretty frequently with deer.

**Comment by SuntooX** [comment] 2021-04-22 12:20
> I, too, am experiencing this. Also Linux. Occasionally happening under other circumstances, but I can replicate it pretty frequently with deer.

Thank gabe it isn't just me.
I've been able to replicate this issue on fresh install with fresh BepInEx and also found the same isssue with the mod "BetterArchery". Whatever is causing this is confusing me a lot.

Oh and if you didn't  already try to check error or crash logs - its a hard crash without unity reporting anything to the log, or generating the crash log.

**Comment by RandyKnapp** [comment] 2021-04-26 13:01
Duplicate of #137

**Closed by RandyKnapp** 2021-04-26 13:01 UTC
