### ISSUE TITLE
2.0.0/.1 compatibility issues with CraftingWithContainers.

### ISSUE THREAD

**Issue by Pinkaminks** [RandyKnapp/ValheimMods#66] opened 2021-03-18 07:49 UTC
Title. Not entirely sure what the update has changed but the CraftingWithContainers mod stops functioning whenever the newer versions are installed. Still works fine on 1.0.5.

**Comment by Nitrinax** [comment] 2021-03-18 09:18
CraftingWithContainers continues to work, but when building, if more than the required amount of materials are available, double the amount of materials is consumed and only the single amount of materials is returned when destroyed. This only happens if Equipment andQuickSlots 2.0.0 / .1 is installed. This error does not exist in the older version 1.0.5. I contacted the author of CraftingWithContainers to, so he can look for a compatibility issue, but i think the problem ist the new Equipment andQuickSlots version.

**Comment by JourneyOver** [comment] 2021-03-18 14:24
Least you some how got it to work @Nitrinax some of us the two mods don't even work together at the moment, unless we disable or downgrade `Equipment And QuickSlots`.. Though https://www.nexusmods.com/valheim/mods/40 seems to work. So whatever `aedenthorn` does is a bit different to not be causing a conflict between the two mods.

**Comment by Razinell** [comment] 2021-03-18 15:47
> Title. Not entirely sure what the update has changed but the CraftingWithContainers mod stops functioning whenever the newer versions are installed. Still works fine on 1.0.5.

Me too exactly.

**Comment by RandyKnapp** [comment] 2021-03-18 15:49
Duplicate of #62

**Closed by RandyKnapp** 2021-03-18 15:49 UTC
Labels: duplicate, mod conflict
